# This is a basic workflow to help you get started with Actions

name: Deploy Hexo blog

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 12.18.0
      - name: Deploy blog
        env:
          Deploy : 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
        run:
          git config --global user.name "zzg-12"
          git config --global user.email "2445422375@qq.com"
          npm install
          npm run bulid
          npm run deploy
